apiVersion: v1
kind: Pod
metadata:
  name: cloud-basic-group-1-0
  namespace: cloud-basic
  labels:
     name: test001-nginx
spec:
  containers:
    - name: nginx
      image: nginx:1.14.0
      imagePullPolicy: IfNotPresent
      ports:
      - name: http
        containerPort: 80
        hostPort: 80

---
